Adding Scenario class and changing structure of configuration file
FIZEMO/FIZEMO pull request #21
Opened 2021-10-24 00:59 UTC by kasia-kacz

Check code refactoring and new Scenario class. I also updated manual.txt file and comments. Check if everything is written clearly and understandable.

2021-10-24 15:03 UTC, Iwo98 commented on scenario.py
> +# Class for one scenario
```suggestion
# Class for a single scenario
```

2021-10-24 15:13 UTC, Iwo98 commented on signal.py
> +#  - signalType: type of processed signal
Dlaczego dajemy tutaj typ sygnału? Czy nie będziemy mieli klas, które będą dziedziczyć po tej klasie? Czy ta zmienna signalType będzie tu ważna?

2021-10-24 15:26 UTC, Iwo98 requested changes
Bardzo mi się podoba, jedynie mam tutaj jakieś pytania i wątpliwości do dodatkowych komentarzy, ale poza tym super.

2021-10-24 15:26 UTC, Iwo98 commented on main.py
>  # Function for loading a json configuration file
Może najpierw dajmy jakie argumenty przyjmuje, a niżej co zwraca? Bo można się zakrecić czytając.

2021-10-24 15:26 UTC, Iwo98 commented on main.py
> +        scenarios.append(config[flow][0])
Może warto napisać czemu tutaj jest to magiczne zero?

2021-10-24 15:26 UTC, Iwo98 commented on main.py
> +# Function for converting tuple obtained from loading a json configuration file to list of Scenario objects
Może znowu tutaj - najpierw co przyjmuje, a niżej co zwraca?

2021-10-24 15:26 UTC, Iwo98 commented on main.py
Super Kasia, teraz to jest meeega czytelne, świetna robota.

2021-10-24 15:26 UTC, Iwo98 commented on main.py
> +DICTIONARY = 1
Tutaj warto dodać komentarz co oznaczają te zmienne.

2021-10-24 15:26 UTC, Iwo98 commented on main.py
> +DICTIONARY = 1
Znaczy jak obejrzałem cały kod, to zrozumiałem, ale wciąż myśle, że warto.

2021-10-24 20:06 UTC, kasia-kacz commented on signal.py
> +#  - signalType: type of processed signal
Potrzebujemy, bo jak będziemy wczytywać plik z sygnałem to program nie wie, jakiego sygnału ma się spodziewać, nazwa pliku może nic nie sugerować. Na podstawie tego typu (będą ściśle określone w manualu) będziemy mogli tworzyć obiekty danych klas dziedziczących po klasie bazowej Signal.

2021-10-25 06:45 UTC, Iwo98 commented on signal.py
> +#  - signalType: type of processed signal
Oki

2021-10-25 06:54 UTC, Iwo98 commented on signal.py
>              self.features.append([attr, value])
Skoro teraz wyżej w argumentach funkcji dałaś wartość defaultową to czy dalej potrzebujemy tego ifa i else? Bo jeśli dobrze rozumiem to jak nie w configu nie będzie żadnej wartości to damy mu te wartość czy wpisana jest jako defaultowa czyli w tym wypadku np „Variance”, to w takim wypadku nigdy nie będzie przypadku, ze nie spelnimy warunku not attr. Dobrze myśle? I to tyczy się wszystkich funkcji tutaj, które maja wartość defaultowa w argumentach.

2021-10-25 07:13 UTC, kasia-kacz commented on signal.py
>              self.features.append([attr, value])
Przy debugowaniu wyszło, że wartość defaultowska umieszczona przy atrybucie odpowiada temu przypadkowi, który chcieliśmy obsłużyć czyli gdy w ogóle w pliku konfiguracyjnym nie ustawiamy outputLabel. Ten if else dotyczył przypadku, gdy string jest pusty, czyli outputLabel: "" I taki przypadek zawarliśmy przy testowaniu pliku konfiguracyjnego, tego pierwszego nie. To już od nas zależy czy chcemy zostawiać pusty string czy chcemy to traktować jako brak nazwy ekstraktowanej cechy i dawać mu znowu defaultowską wartość.

2021-10-25 07:18 UTC, kasia-kacz commented on signal.py
>              self.features.append([attr, value])
Mogę albo usunąć tego ifa I nie obsługujemy przypadku pustego stringa, zmienić warunek ifa na czytelniejszy albo można to tak zmergowac po prostu. Chociaż wydaje mi się że raczej pusty string to przez przypadek ktoś zostawia I lepiej to obslugiwac jakoś.

2021-10-25 07:20 UTC, Iwo98 commented on signal.py
>              self.features.append([attr, value])
Okej okej, czaje. Mhmm, po prostu troszkę to dziwne, że obsługujemy defaultowa wartość, a potem jak ktoś sobie da coś innego - nawet pustego stringa to mu go zamienimy. A może chcą mieć pustego stringa w sumie?

2021-10-25 07:21 UTC, kasia-kacz commented on signal.py
>              self.features.append([attr, value])
No właśnie zastanawialam się nad tym. Dobra, możemy to usunąć, ale trzeba to napisać w manualu jeszcze.

2021-10-25 08:57 UTC, Iwo98 commented on signal.py
>              self.features.append([attr, value])
Usuń, sprawdź czy działa poprawnie i opisz w manualu ze brak tego pola skutkuje nazwaniem tego pola tak jak nazywa się wybrana funkcja, a w innym wypadku będzie dokaldnie taki opis jak przy polu output label

2021-10-25 10:31 UTC, Iwo98 approved these changes

2021-10-25 10:32 UTC, merged